services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    container_name: meowsic-frontend
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./music:/music:ro

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: meowsic-backend
    restart: unless-stopped
    ports:
      - "3457:3457"
    volumes:
      - meowsic-data:/data
      - ./music:/music:ro

volumes:
  meowsic-data:
