services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    container_name: meowsic-frontend

    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - snuggle-net
    volumes:
      - ./music:/music:ro

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: meowsic-backend
    restart: unless-stopped
    ports:
      - "3457:3457"
    networks:
      - snuggle-net
    volumes:
      - meowsic-data:/data
      - ./music:/music:ro

volumes:
  meowsic-data:

networks:
  snuggle-net:
